# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42a0d135eaa43c2ff12709337b2254991be67e9888ed26b1b2ab58a2a69245c7c7e7cdb3017664e337f1a2bc234b9709b7ff9fe31946f4c1549c0c79834b83f0

test:
  secret_key_base: fbea6e7b630203b9c37d875544dbf2f1ac289f40ff9c32acd75a2691d3ebdbfab9e82eb89c6c299f3d70f210b0996324d430b10258ac7d29d732561a7728b456

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
